# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4E1DD
background         #131418
cursor             #BFBBC4

active_tab_foreground     #131418
active_tab_background     #F4E1DD
inactive_tab_foreground   #F4E1DD
inactive_tab_background   #131418

active_border_color   #F4E1DD
inactive_border_color #131418
bell_border_color     #4D5264

color0      #27282D
color1		#4D5264
color2		#676F81
color3		#86767D
color4		#86767D
color5		#A7786F
color6		#A77F76
color7		#E6CCC6
color8		#A18F8A
color9		#676D86
color10		#8A94AC
color11		#B29DA7
color12		#B29DA7
color13		#DFA094
color14		#DEAA9D
color15		#E6CCC6
