capitalization = "Follow"
follow_for_caps_sensitive = false
follow_for_caps_insensitive = false
category = "Celeste"
keyboard = 0
style = 1
mouse_from_center = false
mouse_sensitivity = 50.0
min_press_time = 0
scroll_hold_time = 100
window_title = "NuhxBoard"
update_text_position = true

[display_choice]
id = 66
primary = true
